language: csharp
solution: Semester2/Homework3/3.2/3.2.sln 
mono: none
dotnet: 2.1

before_build:
  - nuget restore Semester2/Homework3/3.2/3.2.sln

build:
  - dotnet build Semester2/Homework3/3.2/3.2.sln

script:
  - dotnet test Semester2/Homework3/3.2/3.2.sln