language: csharp
solution: Semester2/Homework1/1.1/1.1.sln
mono: none

dotnet: 2.1

script:
  - nuget restore Semester2/Homework1/1.1/1.1.sln
  - dotnet build Semester2/Homework1/1.1/1.1.sln
  - dotnet test Semester2/Homework1/1.1/1.1.sln