language: csharp
solution: Semester2/Homework2/2.1/2.1.sln 
mono: none

dotnet: 2.1

install:
  - nuget restore Semester2/Homework2/2.1/2.1.sln

script:
  - dotnet build Semester2/Homework2/2.1/2.1.sln