language: csharp

mono: none
dotnet: 2.1

before_build:
  - nuget restore Semester2/Homework3/3.1/3.1.sln

build:
  - dotnet build Semester2/Homework3/3.1/3.1.sln

script:
  - dotnet test Semester2/Homework3/3.1/3.1.sln
