language: csharp
solution: Semester2/Homework6/6.1/6.1.sln 
mono: none
dotnet: 2.1

before_build:
  - nuget restore Semester2/Homework6/6.1/6.1.sln

build:
  - dotnet build Semester2/Homework6/6.1/6.1.sln

script:
  - dotnet test Semester2/Homework6/6.1/6.1.sln