image: Visual Studio 2017

before_build:
  - nuget restore Semester2/Homework3/3.1/3.1.sln
  - choco install opencover.portable
  - choco install codecov

build:
  project: Semester2/Homework3/3.1/3.1.sln
  verbosity: minimal

test_script:
  - dotnet test Semester2/Homework3/3.1/3.1.sln
  - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"YourTestDll -noshadow" -output:"coverage.xml" -filter:"+[YourSUTNamepace*]* -[YourTestNamespace*]*"