image: Visual Studio 2017

branches:
  only:
    - 3.1

before_build:
  - nuget restore Semester2/Homework3/3.1/3.1.sln

build:
  project: Semester2/Homework3/3.1/3.1.sln

test_script:
  - dotnet test Semester2/Homework3/3.1/3.1.sln