image: Visual Studio 2017

branches:
  only:
    - 1.1

before_build:
  - nuget restore Semester2/Homework1/1.1/1.1.sln

build:
  project: Semester2/Homework1/1.1/1.1.sln

test_script:
  - dotnet test Semester2/Homework1/1.1/1.1.sln